### ISSUE TITLE
libpython error when using "Python in q" functionality

### ISSUE THREAD

**Issue by erichards97** [KxSystems/pykx#35]
**Describe the bug**
When importing PyKx into a q session (i.e. `\l pykx.q`), a `'libpython` error is returned. This can be fixed by symlinking libpython*.so (see below), but this shouldn't be necessary.

**To Reproduce**
Dockerfile
```
FROM ubuntu:22.04

WORKDIR /work

COPY prep/l64.zip /work
COPY prep/kc.lic /work

ENV QHOME=/work/kdb

RUN apt-get update && \
 apt-get install -y python3.10 python3.10-venv libpython3.10 unzip curl
 
RUN unzip l64.zip -d kdb && \
 python3.10 -m venv .venv && \
 . .venv/bin/activate && \
 pip install pykx find-libpython && \
 python -c "import pykx;pykx.install_into_QHOME(to_local_folder=True)" 
```
Then
```
sudo docker build . --tag pykx
sudo docker run --rm -it pykx
```
Then
```
. .venv/bin/activate
kdb/l64/q
\l pykx.q
```
_--> Doesn't work with libpython error_

**To Fix**
```
ln -s /usr/lib/x86_64-linux-gnu/libpython3.10.so.1 /usr/lib/x86_64-linux-gnu/libpython3.10.so
kdb/l64/q
\l pykx.q
```
_--> Does work_

**Expected behavior**
PyKx should work without having to symlink libpython. The find-libpython Python package successfully returns the correct path, and is mentioned in your docs as a dependency. Perhaps this should be used?
```
>>> from find_libpython import find_libpython
>>> find_libpython()
'/usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0'
```

If [L5-12 from embedPy](https://github.com/KxSystems/embedPy/blob/master/p.q#L5) lives on in PyKx, that could explain the issue, as the "L" variable returns the incorrect path to libpython.

**Comment by cmccarthy1** [comment]
Hey @erichards97

Thanks for raising this! We can look into what we can do to improve the experience of this.

We have relied directly on find-libpython in the past (prior to 1.6.1) but we had seen issues with this not finding the correct shared object for the Python version that's being used in complex user environments and on Windows.

There is an environment variable `PYKX_PYTHON_LIB_PATH` which you can set to the path of the shared object that you wish to use should you not want to create the symlink. In your case this would be something akin to

```bash
export PYKX_PYTHON_LIB_PATH= '/usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0'
```

I'll try to provide an update in the week or so once we have had a chance to look into options

**Comment by erichards97** [comment]
Thanks for digging into this @cmccarthy1 .

We've verified that `find-libpython` returns the correct path in all of our setups, so the proposed env var sounds good to us. Please let us know if this makes its way into a future PyKx release.

**Comment by erichards97** [comment]
Hi @cmccarthy1 - do you know if this functionality will be added in a future release? Many thanks

**Comment by cmccarthy1** [comment]
Hey @erichards97,

Yes, the intention is that we'll be adding something for this either in our 3.0 or 3.1 release so will have a fix for this before the end of the year.

**Comment by rianoc-kx** [comment]
PyKX 3.0 been released which includes:

> Addition of support for new environment variable PYKX_USE_FIND_LIBPYTHON which will use the Python package [find_libpython](https://pypi.org/project/find-libpython/) to specify the location from which libpython.[so|dll] will be taken.

https://code.kx.com/pykx/3.0/release-notes/underq-changelog.html#additions
