### ISSUE TITLE
`__setattr__` and `__setitem__` have a different behavior

### ISSUE THREAD

**Issue by Matoran** [KxSystems/pykx#39]
Hi, I'm not sure it's a bug, maybe it's by design.
**Describe the bug**
`__setattr__` and `__setitem__` have a different behavior, one sets to global and the other on a namespace.
https://github.com/KxSystems/pykx/blob/bf05b31d5fe40c1d033bda4566ca34a777f8d536/src/pykx/__init__.py#L170-L191

**To Reproduce**
```python
pykx.q["b"] = 11
pykx.q("show b")
# output is 11
pykx.q.a = 10
pykx.q("show .a")
# output is 10
pykx.q("show a")
# QError: a
```

**Expected behavior**
Shouldn't both have same behavior?

**Comment by rianoc-kx** [comment]
`pykx.q.a` falls under the context interface which is designed for use with namespaces
https://code.kx.com/pykx/3.0/user-guide/advanced/context_interface.html
 
For assigning q variables `pykx.q["a"] =` is the suggested syntax currently.

**Comment by Matoran** [comment]
Thanks for the documentation and explanation, all clear. Will update old pyq code to be compatible.
